version: '3.8'

services:
  bhashasutra-api:
    build: .
    container_name: bhashasutra_container  
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd/logs:/app/BackEnd/logs
      - ./BackEnd/temp:/app/BackEnd/temp
      - ./BackEnd/visualizations:/app/BackEnd/visualizations
      - ./BackEnd/vectordbs:/app/BackEnd/vectordbs  # Add this line for vector databases
    env_file:
      - ./BackEnd/src/.env
    networks:
      - bhashasutra-network
    
  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: bhashasutra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bhashasutra-network

networks:
  bhashasutra-network:
    driver: bridge

volumes:
  postgres_data: